version: '2.4'

services:
  faceembedder:
    volumes:
      - ${DL1_RAW_DIRPATH}:/datasets/raw
      - ${DL1_INTERIM_DIRPATH}:/datasets/interim
      - ${DL1_PROCESSED_DIRPATH}:/datasets/processed
      - ${DL1_LEGACY_DIRPATH}:/datasets/legacy