version: '2.4'

services:
  faceembedder:
    build:
      context: ${PWD}
      dockerfile: ${DOCKERFILE_PATH}
      args:
        - DOCKER_USER_NAME=${DOCKER_USER_NAME}
        - DOCKER_USER_PASS=${DOCKER_USER_PASS}
        - DOCKER_SSH_PORT=${DOCKER_SSH_PORT}
        - PROJECT_DIRPATH=${CONTAINER_PROJECT_DIRPATH}
    runtime: nvidia
    ipc: host
    shm_size: 16gb
    restart: unless-stopped
    tty: true